# Pre-commit configuration using modern tool versions
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        exclude: '^(uv\.lock|poetry\.lock|package-lock\.json|yarn\.lock)$'
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-docstring-first

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.6
    hooks:
      # Run the linter with fixes
      - id: ruff
        args: [--fix]
        files: ^(emotional_processor|tests|scripts)/.*\.py$
      # Run the formatter
      - id: ruff-format
        files: ^(emotional_processor|tests|scripts)/.*\.py$

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        files: ^emotional_processor/.*\.py$
        additional_dependencies:
          - types-PyYAML
          - types-requests
          - torch
          - transformers
          - sentence-transformers
          - qdrant-client
          - loguru
          - pydantic
        # Use pyproject.toml configuration, don't override with args

  # Dockerfile linting
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker
        args: [--ignore, DL3008, --ignore, DL3009, --ignore, DL3013]

  # YAML/JSON/Markdown formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types_or: [yaml, markdown, json]
        exclude: |
          (?x)^(
            \.github/.*\.ya?ml|
            .*\.lock|
            scripts/.*test_conversation\.json
          )$

ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ""
  autoupdate_commit_msg: "[pre-commit.ci] pre-commit autoupdate"
  autoupdate_schedule: weekly
  skip: []
  submodules: false
